#ifndef CONFIG_HPP
#define CONFIG_HPP

#define DEFAULT_CELL_LENGTH 64
#define DEFAULT_CELL sf::IntRect(0, 0, DEFAULT_CELL_LENGTH, DEFAULT_CELL_LENGTH)
#define DEFAULT_LANE \
    sf::IntRect(0, 0, DEFAULT_CELL_LENGTH * 12, DEFAULT_CELL_LENGTH)
#define DEFAULT_SPAWN_INTERVAL sf::seconds(0.5)
#define DEFAULT_LANE_LENGTH 12

// #define MODE_EASY 1.0
// #define MODE_MEDIUM 1.1
// #define MODE_HARD 1.2

#endif  // CONFIG_HPP
