name: build

on:
  push:
    paths_ignore:
      - "README.md"
    branches: [main]
  pull_request:
    paths_ignore:
      - "README.md"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install sfml
        run: |
          sudo apt-get update
          sudo apt-get install libsfml-dev

      - name: Build
        run: |
          mkdir build
          cd build
          cmake ..
          make
